### ISSUE TITLE
Depth data

### ISSUE THREAD

**Issue by PyTorr** [TimmHess/UnrealImageCapture#13] opened 2021-07-14 12:10 UTC
After all **your** help, I was able to capture the wanted images.

One thing I don't understand is how to get the depth values.

When I'm opening the depth (exr files) they look very similar to the segmentation.

How the depth is calculated.

I'm attaching what I tried:
![image](https://user-images.githubusercontent.com/8789891/125618191-e7a7152f-8121-466a-b027-65998a44dd92.png)
![image](https://user-images.githubusercontent.com/8789891/125619753-8be3ac03-ab05-49a8-9490-a732eba46835.png)

**Comment by TimmHess** [comment] 2021-07-14 13:31
Sounds good, I am glad you got it to work for you!

How did you "open" the .exr file? I am using a python script for this purpose with the [`OpenEXR`](https://pypi.org/project/OpenEXR/) lib. This allows loading the file format appropriately, which is an image-like array of float values, where each "pixel" holds the distance-value to the camera while rendering the particular image. (Actually, the values will be integers in scene units (centimeters) if I recall correctly, however, I had to load them as a float type.)

The depth information itself is taken from the depth buffer of the render path, hence the PostProcessMaterial (PP_Depth).

**Comment by PyTorr** [comment] 2021-07-14 17:07
I opened it with openCV.
I will try the other way tomorrow.
Thanks.

**Comment by TimmHess** [comment] 2021-07-14 18:28
I tried the OpenCV approach once too, but my depth information got messed up, even though I don't know why.

**Comment by PyTorr** [comment] 2021-07-15 06:39
I open the image with the code:

`I = OpenEXR.InputFile(path)
dw = I.header()['displayWindow']
size = (dw.max.y - dw.min.y + 1, dw.max.x - dw.min.x + 1)
data = [np.fromstring(c, np.float32).reshape(size) for c in I.channels('RGBA', Imath.PixelType(Imath.PixelType.FLOAT))]
img = np.dstack(data)
img = np.clip(img, 0, 1)
#### convert colour to sRGB
img = np.where(img<=0.0031308, 12.92*img, 1.055*np.power(img, 1/2.4) - 0.055)
return (img*255).astype(np.uint8)`

And get that the depth of the objects is uniform (see attached):
![image](https://user-images.githubusercontent.com/8789891/125740787-00415b92-edac-4045-af7b-2471ee65e3cd.png)

**Comment by TimmHess** [comment] 2021-07-15 08:30
Hey, 
thank you for taking the time to test this to the core! Unfortunately, I cannot reproduce this one either. 

This is the intended PP_Depth material: 
![DepthMaterial](https://user-images.githubusercontent.com/19590182/125755154-c38d9ce9-9208-445d-9aa5-12c732eadc5e.png)

And this is the python script I am using:

``` python
pt = Imath.PixelType(Imath.PixelType.FLOAT)
img = OpenEXR.InputFile(path)
dw = img.header()["dataWindow"]
size = (dw.max.x - dw.min.x +1, dw.max.y - dw.min.y +1)
redstr  = img.channel("R",pt)
red = np.asarray(Image.frombytes("F", size, redstr)).copy()
cap = 1000
red[red>cap] = cap
red /= cap
red = np.asarray(red*255, dtype=np.uint8)
cv2.imshow(...)
```

From which I obtain this final image (converted to unit8 for display purpose):
![img_000000](https://user-images.githubusercontent.com/19590182/125755747-c73034e7-057b-4d49-8add-9e2dd4ba3709.png)

Note that the "cap" is set to merely 1000 units in this image.

**Closed as completed** 2021-07-18 08:21 UTC
